Repository LiliLiu09/CITS5505_AgileWebProject2, pull requests merged in 2024-05, with the labels that each got.

#31 18 design the database
  deliverable/deliverable1/database_design.png
  deliverable/deliverable1/deliverable1.md
  deliverable/deliverable2/deliverable2.md
Labels: deliverable

#33 Add a checkbox for being anonymous
  app/static/css/add_note.css
  app/templates/add_note.html
Labels: enhancement, front-end

#34 Fix the text area bug in the add note page
  app/static/css/add_note.css
Labels: front-end, bug fixed

#35 28 set up api in back end server
  app/__init__.py
  app/api/__init__.py
  app/api/errors.py
  app/api/token.py
  app/api/users.py
  app/app.db
  app/models.py
  migrations/versions/dde9c348810f_remove_email_from_users.py
  requirements.txt
Labels: back-end

#36 1. enabled note content check and label content check. 2. added a clo…
  app/static/css/add_note.css
  app/static/js/add_note.js
  app/templates/add_note.html
Labels: enhancement, front-end

#40 add table send reply labels in models
  app.py
  app/app.db
  app/config.py
  app/forms.py
  app/models.py
  migrations/versions/171c252b4ffe_add_send_note_reply_note_and_labels_.py
  migrations/versions/1d523e191313_change_post_table_name_to_be_send_note.py
  migrations/versions/330bd794a257_add_fk_in_reply_note.py
  migrations/versions/d0422b253681_change_table_name.py
  migrations/versions/e22dfa71b59c_remove_timestamp.py
Labels: enhancement, back-end

#43 41 add send message reply message add labels in routes
  app.py
  app/app.db
  app/forms.py
  app/models.py
  app/routes.py
  app/templates/flask_index.html
  app/templates/flask_label.html
  app/templates/flask_reply.html
  app/templates/flask_send.html
  migrations/alembic.ini
  migrations/versions/112d1590197d_removed_label_table.py
  migrations/versions/171c252b4ffe_add_send_note_reply_note_and_labels_.py
  migrations/versions/1d523e191313_change_post_table_name_to_be_send_note.py
  migrations/versions/330bd794a257_add_fk_in_reply_note.py
  migrations/versions/349d217f69dc_.py
  migrations/versions/541418d7cb22_posts_table.py
  migrations/versions/d0422b253681_change_table_name.py
  migrations/versions/dde9c348810f_remove_email_from_users.py
  migrations/versions/e22dfa71b59c_remove_timestamp.py
Labels: enhancement, back-end

#46 37 static check and reply note
  app/static/css/add_note.css
  app/static/css/check_and_reply.css
  app/static/images/rectangle.png
  app/static/js/check_and_reply.js
  app/static/js/reply_random.js
  app/templates/check_and_reply.html
  app/templates/reply_random.html
Labels: front-end

#51 static check reply page done
  app/static/css/check_reply.css
  app/static/images/reply_envelop.png
  app/static/js/check_reply.js
  app/templates/check_reply.html
  app/templates/index.html
Labels: front-end

#52 44 add getpost send message in api
  app/api/users.py
  app/app.db
  app/models.py
  app/routes.py
  app/templates/flask_index.html
Labels: back-end

#53 static open note answer done
  app/static/css/open_note_answer.css
  app/static/js/open_note_answer.js
  app/templates/check_reply.html
  app/templates/open_note_answer.html
Labels: front-end

#54 static search for a note done
  app/static/css/add_note.css
  app/static/css/reply_note_entry.css
  app/static/js/check_and_reply.js
  app/static/js/reply_note_entry.js
  app/static/js/reply_random.js
  app/templates/reply_note_entry.html
Labels: front-end

#55 update the static pages diliverable2
  app/static/css/add_note.css
  app/static/css/check_and_reply.css
  app/static/css/index.css
  app/static/css/open_note_answer.css
  app/static/css/reply_note_entry.css
  app/static/css/reply_random.css
  app/templates/index.html
  deliverable/deliverable2/Figma Design By Sally Chen.png
  deliverable/deliverable2/deliverable2.md
  deliverable/deliverable2/static pages/Add_label.png
  deliverable/deliverable2/static pages/Check-answer.png
  deliverable/deliverable2/static pages/Check_reply.png
  deliverable/deliverable2/static pages/Index.png
  deliverable/deliverable2/static pages/Login.png
  deliverable/deliverable2/static pages/Open_answer.png
  deliverable/deliverable2/static pages/Register.png
  deliverable/deliverable2/static pages/Reply_entry.png
  deliverable/deliverable2/static pages/Reply_random.png
  deliverable/deliverable2/static pages/Search_note.png
  deliverable/deliverable2/static pages/Wrtie_note.png
Labels: deliverable, front-end

#56 9 css redup of loginregister
  app/static/css/login&register.css
  app/static/css/login.css
  app/static/css/register.css
  app/static/css/reset.css
  app/templates/login.html
  app/templates/register.html
Labels: enhancement, front-end

#60 bug fixed for this issue
  app/static/css/open_note_answer.css
  app/templates/open_note_answer.html
  app/templates/register.html
Labels: front-end, bug fixed

#99 add copyright reserved to login and register
  app/static/css/login&register.css
  app/templates/login.html
  app/templates/register.html
Labels: enhancement, front-end

#101 100 fix bugs
  .gitignore
  README.md
  app/.env
  app/api/users.py
  app/models.py
  tests/test_api.py
Labels: documentation, bug fixed
