Repository LiliLiu09/CITS5505_AgileWebProject2, pull requests merged in 2024-04, with the labels that each got.

#3 1 static login
  .gitignore
  app/static/css/login.css
  app/static/css/reset.css
  app/static/fonts/Apple Chancery.ttf
  app/static/fonts/BanksScript.otf
  app/static/images/github.svg
  app/static/images/login-img.png
  app/static/images/login-logo.png
  app/static/images/logo.png
  app/templates/login.html
Labels: good first issue, front-end

#8 2 static register
  app/static/css/register.css
  app/templates/register.html
Labels: front-end, bug fixed

#7 4 static index
  app/static/css/index.css
  app/static/images/arrow1.png
  app/static/images/arrow2.png
  app/static/images/card1.png
  app/static/images/card2.png
  app/static/images/card3.png
  app/static/images/default-avatar.png
  app/static/images/index-main.png
  app/static/images/menu-button.png
  app/static/js/index.js
  app/templates/index.html
Labels: front-end

#13 11 static add notes
  app/static/css/add_note.css
  app/static/images/add_note.png
  app/static/js/add_note.js
  app/templates/add_note.html
  app/templates/index.html
Labels: front-end

#14 12 add note word limit
  app/static/css/add_note.css
  app/static/fonts/WorstveldSling.otf
  app/static/js/add_note.js
  app/templates/add_note.html
Labels: enhancement, front-end

#20 15 improve the set up for flask environment basic config for database
  app.py
  app/__init__.py
  app/app.db
  app/config.py
  app/forms.py
  app/models.py
  app/routes.py
  app/templates/base.html
  app/templates/flask_index.html
  app/templates/flask_login.html
  app/templates/flask_register.html
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/541418d7cb22_posts_table.py
Labels: back-end

#22 add register function in forms.py and routes.py
  app/app.db
  app/forms.py
  app/routes.py
  app/templates/flask_login.html
  app/templates/flask_register.html
Labels: enhancement, back-end, priority-high

#23 17 add label to the note
  app/static/css/add_note.css
  app/static/js/add_note.js
  app/templates/add_note.html
Labels: enhancement, front-end
